dist: trusty
language: node_js
node_js:
  - '8'
  - '7'

branches:
  only:
    - master

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb

install:
  - npm install
  - npm install -g firebase-tools
  - npm install -g coveralls

script:
  - npm run lint
  - npm run build
  - npm run coverage

after_success:
  - 'if [ "${TRAVIS_NODE_VERSION}" = "8" ]; then cat ./coverage/lcov.info | coveralls ; fi'

deploy:
  provider: firebase
  token:
    secure: "dst1ANWICgnl5zopu2O1k4t4EIrPYN6qZr5ak9h52EuteqBXovDTV2TeTrL6F3beBGTbjKpSUrO/Fm+qC6sm1w1RYsfInWJ1w7vo3Oai7wZhvqGk4Hq2nmAHZedPSMURhhsQsWu4jof7n7s1ArMpB33LxNbI/06iz2MUimBaMsiEF9c4xalouIfK4c2BjUvC0cqX3MaEKa3KRK8ZiO5LxNrf8sTzN66NUAkkOoChEG/a+89BarYVBXIwoqNH08S2/b+nzxKKTCVGKgWpkrgfd5uNUXBtKsInGeM9U8/MCqERdJywgvhe5QngZCWjkI3Er9f3n0n11FZ8aoK/oHR+2LQCBseLHrUXZOBbYHsO7g2/Z4/9qaongSOxoDmTX2Vb2NR3lMOrRilSl2BB7CDTVX+YFWvaV/weU1CEdXfb+QX8VACrMFmvGiX/52189cCGiamh9x1cyfamECz/1s9jJyaM6we/+6p7DwG7Ja+tUN9KCmCSq5xyxigZxY8k6ZAp5ujWAv2XgY/0XtOgvYqn6B48LWhOsWbPXs74mpe5TDOeaDx/fzqMpPTAAm5dcpvNZypiByCtIVMOyD3ZQ4UTCO7CNsAk9x3gXHIIcZ4Auy6rJgJMknxHju8hPRtiA6+reBdan8TpJAys51CUbkL6iABfqZ63hTQhN7lBCdpSDBg="